### ISSUE TITLE
[LibOS, Pal/Linux-SGX] Remote Attestation: Discussion of PRs

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#1365]
Previously, we had Thomas working on this PR that exposes Remote Attestation to the LibOS and application layers (via `/dev/attestation/` pseudo-FS): https://github.com/oscarlab/graphene/pull/1284.

I am taking over this PR. Currently I'm leaning towards submitting a series of PRs (rebased on the current master) that will look like this:

- [x] PR 1 (#1366): Tiny bug fixes of SGX-related functions and structs. In particular:
    - `enclave_framework.c`: adding `sgx_get_report()`
    - `Linux-SGX/pal_linux.h`: assert on `pal_enclave_state` being 64B
    - `sgx_api.h`: better comments on `sgx_report()` and `sgx_getkey()`
    - `sgx_arch.h`: more fields in `sgx_report_body_t`
    - renaming `aesm_targetinfo` -> `qe_targetinfo`, `init_aesm_targetinfo` -> `init_quoting_enclave_targetinfo`

- [x] PR 2 (https://github.com/oscarlab/graphene/pull/1373): Removing most of Chia-Che's "Simple RA" code (won't be needed since useless self-verification will be replaced by pseudo-FS RA):
    - Removing `init_trusted_platform()`
    - Changing `ocall_get_attestation()` to return IAS header and report
    - Removing `sgx_attestation_t` and changing `ms_ocall_get_attestation_t`
    - Removing `parse_x509{_pem}()`
    - Significantly simplifying `sgx_verify_platform()` and renaming to `sgx_get_attestation()`
    - Significantly simplifying `contact_intel_attest_service()` to return IAS header and report instead of parsing them
    - `pal.h`: removing `attestation_status` and `attestation_timestamp`

- [x] PR 3 (#1367): Introduce `get_quote()` Linux-SGX PAL functions (as preparation for pseudo-FS RA):
    - `ocall_get_quote()`
    - `sgx_get_quote()`
    - `sgx_ocall_get_quote()`
    - `ms_ocall_get_quote_t` and `OCALL_GET_QUOTE`
    - `retrieve_quote()`

- [x] PR 4 (#1383): Introduce `DkAttestationReport()` and `DkAttestationQuote()` PAL APIs:
    - stubs for Skeleton and Linux PALs
    - `Linux-SGX/db_misc.c`: `_DkAttestationReport()` and `_DkAttestationQuote()`

- [x] PR 5 (#1392): Introduce `/dev/attestation/` pseudo-FS in LibOS:
    - new `shim_attestation.h`
    - new `fs/dev/attestation.c`
    - new RA test under `test/regression`

**Comment by mkow** [comment]
Sounds good, modulo two things:
* Shouldn't `contact_intel_attest_service` be removed? See https://reviewable.io/reviews/oscarlab/graphene/1284#-M-lPDj23wipOmUsWfTq.
* We need to discuss what should be a part of this interface to the enclave (also, see the linked discussion)

**Comment by dimakuv** [comment]
Let's discuss the RA interface here.

Currently, I only looked at how to split and simplify the RA PR from Thomas (#1284). I am open to modifications to that code.

Please leave your answers:

1. Should we remove the communication with IAS from Graphene code base? (PR 2)

2. Should we remove the communication with the (local) Quoting Enclave (via AESM service) from Graphene code base? (PR 3)

3. Should we introduce pseudo-FS APIs for Local Attestation purposes, so that the application layer can access `EREPORT` and `EGETKEY` to perform local attestation? (This is helpful for proxy enclave that does remote attestation on behalf of Graphene, as in Golem/ITL case.) (PR 5)

4. Should we keep `sgx.ra_client_{spid,key,linkable}` fields in the Graphene manifest or remove them?

**Comment by mkow** [comment]
1. Yes, it's mostly useless, because you need the API key to contact IAS, which shouldn't be leaked to any other party except the enclave creator (and we're still *before* remote attestation, so we can't provision any secrets yet). The only case where this would make sense would be the case where the author self-hosts some enclaves, but I don't think this justifies having this feature.
2. I'm not sure, but it probably can stay.
3. Sounds useful, but I'm not sure if we want to have it on this level. I'd prefer an API which doesn't expose any SGX internals to the user app, so that we can easily port it to other TEEs in the future.
4. Remove, they shouldn't be leaked to the enclave user.
5. I'd definitely prefer the latter, assuming we'll manage to design a reasonable one.

Ad IAS communication, @omeg will try to create a PR this week with our tools+libs which can talk to IAS, pretty-print the structures etc. This way we'll have all the code required for remote attestation in our repo, despite removing the code which talks to IAS from the enclave.

**Comment by dimakuv** [comment]
OK, just to recap (see also nice explanations at http://www.sgx101.com/portfolio/remote_attestation/). We have three structs used for Remote Attestation:
1. REPORT: identification of our Graphene enclave, created via `EREPORT(quoting-enclave-target-info, random-app-64b-data)`. Intended for consumption by the Quoting Enclave.
2. QUOTE: created by the Quoting Enclave based on the REPORT (Graphene enclave communicates with Quoting Enclave via AESM, sending protobuf-request with REPORT and receiving QUOTE with REPORT embedded). Intended for consumption by IAS/other attestation service.
3. ATTESTATION: created by IAS/other attestation service based on the QUOTE (Graphene enclave sends the QUOTE to some proxy/special library that forwards this QUOTE to the attestation service). Intended for consumption by the end user (verifier/challenger).

With our pseudo-FS interface, we only want for the application to be able to get REPORT and QUOTE. (Then the application may want to forward the REPORT or the QUOTE to some helper/proxy or even directly to the end user.) In other words, there will be no ATTESTATION struct available in Graphene.

This is what I'm currently doing:

1. Adding REPORT to the pseudo-FS. Resolved purely inside LibOS since only needs `EREPORT`; no changes or new APIs in PAL.

2. Adding QUOTE to the pseudo-FS. Resolved via the new API `DkGetQuote()` in PAL. This requires communication with Quoting Enclave via AESM, so there are also collateral new functions like `init_quoting_enclave_targetinfo()` and `connect_aesm_service()` and `request_aesm_service()`.

3. Removing IAS communication completely. The ATTESTATION stuff must be implemented in the application layer.

**Comment by dimakuv** [comment]
Regarding "generic API vs SGX-specific API". I will currently develop an SGX-specific API in my PRs, and we'll go from there.

**Comment by dimakuv** [comment]
> Should we keep `sgx.ra_client_{spid,key,linkable}` fields in the Graphene manifest or remove them?

One thing I didn't realize is that these fields are used for different purposes:

- `sgx.ra_client_spid` and `sgx.ra_client_linkable` are used during QUOTE retrieval from the Quoting Enclave via AESM; see `retrieve_verified_quote(): REQUEST__GET_QUOTE_REQUEST__INIT`.

- `sgx.ra_client_key` (called `subkey` in Graphene) is used only during ATTESTATION retrieval from IAS; see `contact_intel_attest_service(): Ocp-Apim-Subscription-Key: %s`.

Given that we want to have QUOTE retrieval but not ATTESTATION retrieval, we must remove only one field: `ra_client_key` and leave the other two fields. (NB: This whole discussion is only for EPID, I didn't look at ECDSA yet.)

**Comment by omeg** [comment]
SPID and quote sign type are included in the quote and are not secrets AFAIK. The API key is secret so probably shouldn't be in the manifest.
