### ISSUE TITLE
Rewrite GDB integration

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#1814]
## Description of the problem

Current GDB integration has a lot of bugs, especially the Linux-SGX part.

## Known bugs/issues

- [x] Starting the debuggee causes a spam of logs about SIGILL, which triggers GDB pagination and requires manual scrolling through them. Fixed by #1828.
- [x] On Linux PAL there's an annoying prompt on each GDB start generated by one of our scripts. Fixed by #1828.
- [x] Attaching to an already running process on Linux-SGX misses symbols for all modules loaded so far. Fixed by #1853.
- [x] Breakpoints in Linux-SGX doesn't work until one breaks (e.g. using Ctrl+C) the execution while inside enclave. Fixed by #1853.
- [x] ~#794 (unloading of modules isn't communicated back to GDB, only loading)~ (I think I misunderstood this one, seems to be a mem leak in LibOS `link_map` handling, not directly related to GDB integration)
- [x] ~GDB crashes from time to time with our SGX integration, but it's hard to say if it's our bug or GDB's.~ Haven't reproduced recently, removing this point for now.
- [x] Stack walking is not always correct, probably some of our .cfi directives are slightly off (I think they are wrong in `__morestack` function, but I'm not sure). Linux PAL fixed by #1864. Linux-SGX fixed by #1868.
- [x] Extended register support - looking at sgx_gdb.c it seems that extended registers are not supported at all, so most likely it's not possible to debug enclave code which uses e.g. floating point registers. Fixed by #1874.
- [x] Symbols seem to have incorrect filenames assigned, which makes it hard to use ones which are defined multiple time, like `main()`, e.g.: (see the addresses)
  ```
  (gdb) p 'sgx_main.c'::main
  $3 = {int (int, char **, char **)} 0x556ac9dd36a0 <main>
  (gdb) p 'bootstrap.c'::main
  $4 = {int (int, char **, char **)} 0x556ac9dd36a0 <main>
  ```
  Seems to be a bug in older GDBs. Works correctly on GDB 9.2 (see @pwmarcz comment below).
- [ ] Remove glibc modification of `register_library()` (https://github.com/oscarlab/graphene/blob/v1.1/LibOS/glibc-patches/glibc-2.31.patch#L104)
  PAL can notify the GDB python script on startup about the main executable and interpreter (ld.so dynamic linker) in enclave. Then the python script can monitor `_r_debug` of ld.so in enclave, and register loaded library on behalf of ld.so in enclave in GDB (similar change is needed for Pal/Linux).
  ```diff
  diff --git a/elf/dl-load.c b/elf/dl-load.c
  index a6b80f93957199e1ef2bcbbcc12302830caae978..92ac9703f750755e350c86fc13fd382347931950 100644
  --- a/elf/dl-load.c
  +++ b/elf/dl-load.c
  @@ -73,6 +73,8 @@ struct filebuf
   #include <dl-prop.h>
   #include <not-cancel.h>
 
  +#include <glibc-version.h>
  +
   #include <endian.h>
   #if BYTE_ORDER == BIG_ENDIAN
   # define byteorder ELFDATA2MSB
  @@ -1390,6 +1392,9 @@ cannot enable executable stack as shared object requires");
     DL_AFTER_LOAD (l);
   #endif
 
  +  /* register the library to SHIM */
  +  register_library(l->l_name, l->l_addr);
  +
     /* Now that the object is fully initialized add it to the object list.  */
     _dl_add_to_namespace_list (l, nsid);
  ```
  In Pal/Linux-SGX case
   ```
   r_debug of ld.so in untrusted code <---- gdb directly handles
   Pal/LibOS/main exec/ld.so in enclave <--custom notification: gdb python script handles and register it to gdb
   r_debug of ld.so in enclave <-------------gdb python script monitors r_debug of ld.so which. the script knows about based on the custom notification. and register mapping to gdb.
   ```

  In Pal/Linux case
   ```
  r_debug of libpal.so <------ gdb directly handles
  LibOS/main exec/ld.so <--- update r_debug of libpal.so. So gdb directly handles it.
                                               custom notification: gdb python script knows about those mapping
  r_debug of ld.so <---------- gdb python script monitors of r_debug of ld.so and register mapping to gdb
   ```

## Missing features

- [ ] Would be good to add a few Graphene-specific commands to gdb console to support better introspection of Graphene's state.

## Missing tests

- [x] We should test the integration in CI, especially for regressions in .cfi directives (which already happened in the past). Implemented in #1868.

**Comment by mkow** [comment]
FYI: I updated the list with 2 more bugs.

**Comment by pwmarcz** [comment]
>Symbols seem to have incorrect filenames assigned, which makes it hard to use ones which are defined multiple time, like main(), e.g.: (see the addresses) 

That is pretty weird. 

* GDB does seem to recognize the functions:

```
(gdb) info functions ^main$
All functions matching regular expression "^main$":

File bootstrap.c:
int main(int, const char **, const char **);

File sgx_main.c:
int main(int, char **, char **);
```

* The function from program is visible when referred to by address:

```
(gdb) info symbol 0x40060d
main in section .text of /home/pawel/graphene/LibOS/shim/test/regression/bootstrap
```

* Breakpoints (`bootstrap.c:main`) seem to work (after my PR #1853)

* Just in case, this applies to other function names defined in PAL, not only `main`

* `maint info symtabs` is correct as far as I can tell, i.e. containes the right source paths; `maint print symbols symbols.txt` also produces a dump containing both `main` functions

GDB does not seem to consider any of the files added by us "shared libraries", maybe that's the problem?

I am testing this on a pretty old gdb (GDB 7, under Ubuntu 16), so maybe it's something fixed in a newer version?

**Comment by mkow** [comment]
> I am testing this on a pretty old gdb (GDB 7, under Ubuntu 16), so maybe it's something fixed in a newer version?

Sounds like a good idea to test with GDB from master / the most recent release. GDB is quite buggy.

**Comment by pwmarcz** [comment]
Okay, the newest release (GDB 9.2) fixes this.
```
(gdb) p main
$1 = {int (int, const char **, const char **)} 0x40060d <main>
(gdb) p 'bootstrap.c'::main
$2 = {int (int, const char **, const char **)} 0x40060d <main>
(gdb) p 'sgx_main.c'::main
$3 = {int (int, char **, char **)} 0x5578887e66cc <main>
```

**Comment by pwmarcz** [comment]
I found out that having at least GDB 8.2 would simplify the integration, because it has an `add-symbol-file -o <offset>` command which works well without listing all the sections (see [this comment](https://github.com/pwmarcz/graphene/blob/800e17e33c42e9989fffa5fc6637737c5c151e54/Pal/src/host/Linux-SGX/sgx_rtld.h#L18) for more context). There is also the bug with symbol namespaces mentioned above, and likely  other bugs and missing useful features.

I talked with @mkow about this and he suggested dropping support for older GDB versions. That would require the users to either use a newer system, or build their own GDB. Note that Ubuntu 18.04 bundles GDB 8.1, which is still too old.

A minor difficulty is that the `pal_loader` would need to know the path to GDB. Also, GDB installed in a custom location also requires an additional `-data-directory` parameter.

I think that's a good idea, but I would also add GDB to our builds (same as we build glibc and gcc), because I think we should have a regression test to check symbol loading, stack frames and other things that break often. A test like that should run on a specific GDB version.

What do you think? @mkow @boryspoplawski @dimakuv @yamahata

**Comment by boryspoplawski** [comment]
Dropping support for Ubunut 16 - gdb 7 - sounds like a good idea if that's a blocker, but I think we should support the default version from Ubuntu 18. Forcing newcomers to compile their own gdb version sounds pretty discouraging.

**Comment by mkow** [comment]
As Paweł already mentioned, +1 from my side to drop support for old GDBs.

> Forcing newcomers to compile their own gdb version sounds pretty discouraging. Otoh if we added gdb to our builds ...

Remember that this isn't a feature for users, but for developers, and only on older distros. I don't think compiling GDB from step-by-step instructions is a high bar, especially for someone who's trying to help developing such a low-level project.

**Comment by yamahata** [comment]
+1 for dropping ubuntu 16, (and adding ubuntu 20.04 which comes with gdb 9. )

Personally I’m fine with only supporting gdb only on  20.04.
For developer, probably 18.04 support is desirable.

**Comment by woju** [comment]
FWIW, buster (debian 10) has 8.2

**Comment by dimakuv** [comment]
+1 for asking GDB of at least v8.2. I guess there are no problems using it on older systems like Ubuntu 18.04 (most our development is on this OS distro)?

> I think that's a good idea, but I would also add GDB to our builds (same as we build glibc and gcc), because I think we should have a regression test to check symbol loading, stack frames and other things that break often. A test like that should run on a specific GDB version.

How long does it take to build GDB? If it's similar to say GCC, then we should *not* put it in our Jenkins -- it will take hours just to build (and we have very weak machines in our Jenkins). I think it is reasonable to simply ask devs to upgrade to GDB 8.2. Testing in Jenkins would be nice, but I'd prefer to at least install the package instead of building (so, wait for Ubuntu 20.04 support in our Jenkins?).

**Comment by pwmarcz** [comment]
>How long does it take to build GDB? If it's similar to say GCC, then we should not put it in our Jenkins -- it will take hours just to build (and we have very weak machines in our Jenkins). I think it is reasonable to simply ask devs to upgrade to GDB 8.2. Testing in Jenkins would be nice, but I'd prefer to at least install the package instead of building (so, wait for Ubuntu 20.04 support in our Jenkins?).

It takes about 9 minutes on my machine, so yeah, seeing how Jenkins is going to be slower, it might be best to wait until we support Ubuntu 20.04...

I wouldn't *require* newer GDB until we have means of testing it, though.

**Comment by pwmarcz** [comment]
I'm going through a list of (uncommented) default options for GDB. There are two sets of commands, one for Linux, one for Linux-SGX. I want to reconsider them, remove some, and add comments to the rest.

Generally I'd rather go back to default GDB behaviour unless there are good, Graphene-specific reasons to keep something.

Can you help me understand them? Here is the list with my proposed resolutions.

* `set auto-load off` (Linux only) - Disables auto-loading all kinds of scripts: gdbinit, scripts supplied by binary etc.

  * Remove. And reconsider if there are known incompatibilities.

    (One known incompatibility is trying to load `libthread_db` for inner pthread library, it outright breaks on newer GDB. I will disable that and add a comment.)

* `handle SIGKILL pass print stop`

  * Remove. What does it do? Does it even work? SIGKILL shouldn't be possible to catch.

* `set disable-randomization off` - Enable address space randomization when loading libraries.

  * Keep. Unlike regular applications, Graphene does a lot of linking by itself, and it depends on where the initial binary is loaded, so I would keep ASLR enabled to catch issues earlier.

* `set schedule-multiple on` - Make `continue` and `next` resume all threads.

  * Keep. This seems to be necessary because of IPC threads: otherwise `continue` on even a simple program will keep waiting for the IPC thread before exit, which is pretty confusing to GDB user.

* `set follow-exec-mode same` (Linux-SGX only) - do not create a new GDB inferior, but keep attached to current process.

  * I'm confused, does Graphene use system exec at all?

* `set follow-fork-mode child`, `set detach-on-fork off`

  * Do you know the rationale behind this? I tried to experiment with turning it off, but GDB seems very unreliable around multiple Graphene processes anyway, and sometimes freezes on program exit.

* `set displaced-stepping off` (Linux-SGX only) - "Displaced stepping is a way to single-step over breakpoints without removing them from the inferior, by executing an out-of-line copy of the instruction that was originally at the breakpoint location. It is also known as out-of-line single-stepping."

  * Keep under Linux-SGX. Stepping over in-enclave code doesn't work otherwise: you can't just execute an out-of-line copy of an instruction, you have to resume the process so that it goes back to the enclave.

**Comment by pwmarcz** [comment]
One more:

* Breakpoints on `pal_start` (`set scheduler-locking off`) and `vfork` (`set scheduler-locking on`). Linux only. Is that needed?

**Comment by mkow** [comment]
> SIGKILL shouldn't be possible to catch.

I think a debugger may still catch it (a process itself can't, but that's a different case). But I'm not 100% sure. Also, no idea why we'd want to change defaults here.

> I'm confused, does Graphene use system exec at all?

I think currently it doesn't, maybe in the past it did?

**Comment by pwmarcz** [comment]
Regarding SIGKILL: I tried `kill -9` on a Graphene process running under GDB, the result is the same with or without the option (process exits and GDB prints a message about SIGKILL).

**Comment by mkow** [comment]
Ok, seems that's actually the case, so this option doesn't make any sense:

> SIGKILL does not generate signal-delivery-stop and therefore the tracer can't suppress it. SIGKILL kills even within system calls (syscall-exit-stop is not generated prior to death by SIGKILL). The net effect is that SIGKILL always kills the process (all its threads), even if some threads of the process are ptraced.

**Comment by pwmarcz** [comment]
In the issue:

>Remove glibc modification of register_library()

As mentioned in https://github.com/oscarlab/graphene/pull/2086#pullrequestreview-569209968, I think the solution proposed here (monitoring `_r_debug`) is not worth it: it accounts only for some ELFs loaded (i.e. not Graphene or LibOS), and it's quite useful to have a single data structure in PAL with *all* the debug maps, which we wouldn't have with the proposed solution. Also, SGX profiling depends on it. Right now, I think hooking into `register_library` is simpler than the alternative.

**Comment by mkow** [comment]
The glibc modification point was added by @yamahata, so let's wait for his comment.

**Comment by yamahata** [comment]
It seems major effort to remove register_library().
Given we're not ready for upstreaming ot glibc, I'm fine with register_library().
At least given the kind of change, it would be better to discuss with glibc folks for long term direction.

**Comment by dimakuv** [comment]
Agreed with most of the analysis. Some points:

- `set disable-randomization off` -- isn't it the default? I would prefer to just use the defaults from GDB, and only keep those that differ from the defaults. But yes, I didn't experience much problems with randomization, quite helpful.
- `set schedule-multiple on` -- isn't it a default? I always start in this mode and then at some point when needed switch to `set scheduler-locking on`.
- `set follow-exec-mode same` -- I think this is useless. I remember trying it, but I don't think this changed anything.
- `set follow-fork-mode child`, `set detach-on-fork off` -- just keep the defaults. Every time I debug a multi-process app, I set them explicitly. Maybe I got used to Graphene's debugging but I don't experience much problems with these settings (I was once able to get into the third child of the second child under SGX by doing the right combination of this commands :)).
- `set displaced-stepping off` -- should be kept under SGX.

> Breakpoints on pal_start (set scheduler-locking off) and vfork (set scheduler-locking on). Linux only.

Never heard of it. No idea why it's there.

**Comment by boryspoplawski** [comment]
>     * `set disable-randomization off` -- isn't it the default? I would prefer to just use the defaults from GDB, and only keep those that differ from the defaults. But yes, I didn't experience much problems with randomization, quite helpful.
`on` is the default (notice it's `disable-randomization` so default is to have aslr off).
>     * `set schedule-multiple on` -- isn't it a default? I always start in this mode and then at some point when needed switch to `set scheduler-locking on`.
No, the default is `off`. I think this option refers to scheduling multiple processes and `scheduler-locking` is about threads in the current process.
>     * `set follow-exec-mode same` -- I think this is useless. I remember trying it, but I don't think this changed anything.
This is the default :) Also afaik it only affect restarting, which tbh I never use in gdb with graphene.
>     * `set follow-fork-mode child`, `set detach-on-fork off` -- just keep the defaults. Every time I debug a multi-process app, I set them explicitly. Maybe I got used to Graphene's debugging but I don't experience much problems with these settings (I was once able to get into the third child of the second child under SGX by doing the right combination of this commands :)).
I think `follow-fork-mode` is useless with `set detach-on-fork off`.

**Comment by pwmarcz** [comment]
>set disable-randomization off -- isn't it the default? I would prefer to just use the defaults from GDB, and only keep those that differ from the defaults. But yes, I didn't experience much problems with randomization, quite helpful.

GDB **disables** ASLR by default, I think that usually helps because you have a more repeatable experience (the same pointer values etc.) However, it's also a significant difference from a non-GDB run, and I think that matters for Graphene more than for regular programs. Which is why I'd rather keep ASLR enabled.

> I think this option refers to scheduling multiple processes and scheduler-locking is about threads in the current process.

You're right, I misread the descriptions before.

```
(gdb) help set schedule-multiple 
Set mode for resuming threads of all processes.
When on, execution commands (such as 'continue' or 'next') resume all
threads of all processes.  When off (which is the default), execution
commands only resume the threads of the current process.  The set of
threads that are resumed is further refined by the scheduler-locking
mode (see help set scheduler-locking).
```
```
(gdb) help set scheduler-locking 
Set mode for locking scheduler during execution.
off    == no locking (threads may preempt at any time)
on     == full locking (no thread except the current thread may run)
          This applies to both normal execution and replay mode.
step   == scheduler locked during stepping commands (step, next, stepi, nexti).
          In this mode, other threads may run during other commands.
          This applies to both normal execution and replay mode.
replay == scheduler locked in replay mode and unlocked during normal execution.
```

So I would keep `schedule-multiple` off (as it is by default) and remove the follow-fork options, as @dimakuv says, if you want to debug multiple processes then you probably want to set them as needed anyway.

As for scheduler locking, the default mode is `replay`, so normally it's unlocked. I think that's sensible, especially since even single-threaded programs need an IPC thread under Graphene, and Graphene waits for its completion before exit. And the less customizations we have for GDB, the better.

**Comment by dimakuv** [comment]
Yes, agreed with everything.

**Comment by dimakuv** [comment]
Is this issue still relevant? I don't think we had any problems with GDB integration recently, and a small patch in Glibc doesn't hurt.

I would consider GDB integration done.

**Comment by mkow** [comment]
Let's ask @pwmarcz to decide.

**Comment by pwmarcz** [comment]
I'm going to close this. In the previous comments to this issue, we agreed to leave the glibc patch as is.
