### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by woju** [oscarlab/graphene#2289]
Development:
- [x] Jenkins split, stage 1 (#1858)
- [x] Jenkins split, stage 2 (#1859)
- [x] Initial meson implementation (#1879)
- [x] Python packaging (#1909)
- [x] Remove submodules (#1997)
- [x] First meson options (#2003)
- [ ] Manifest preprocessor (#2288)
- [ ] Make testsuites test installed graphene (WIP #2064, probably will be abandoned)
- [ ] Jenkins split, stage 3: make CI test installed graphene
- [x] packages.grapheneproject.io/distfiles (#2119, #2280)
- [ ] Meson wraps, deprecate `Scripts/download`
- [ ] Full meson, remove makefiles
- [ ] `meson dist` tarballs
- [ ] `debian/`, `.spec`
- [x] repo (packages.grapheneproject.io), build infrastructure

Documentation:
- [ ] `NEWS`/`ChangeLog`/whatever
- [ ] new installation procedure
- [ ] new building procedure
- [ ] guide for distro maintainers/packagers

Release:
- [ ] maintainer scripts for releasing
- [ ] make a release
