### ISSUE TITLE
Security mitigations and hardening

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#2506]
### Mitigations/sanitizations
- [ ] We need better sanitization of OCALL arguments. Current version most likely is not dangerous, but there's a chance that some apps may be manipulated this way into doing something unexpected. See #1236.

### Bug detection
- [ ] Run tests with sanitizers in CI (see #2106).
- [ ] Run some linters in CI. Problem: most have high false-positive ratios.
- [ ] Check for TOCTOU bugs introduced through compiler optimizations (#635; most relevant for OCALLs).

**Comment by boryspoplawski** [comment]
The TOCTOU part is already solved, see the last comment in #635.

**Comment by mkow** [comment]
Right, I updated that point.

**Comment by dimakuv** [comment]
From what I understand, only the first item ("We need better sanitization of OCALL arguments") must be resolved for the release (so priority P0 or P1). The rest (sanitizers/linters) is to be added after the release (so priority P2). For this reason, I'm marking this whole issue as P2.

Notice that https://github.com/oscarlab/graphene/issues/1236 linked to the first item is already marked as P0.

**Comment by mkow** [comment]
Yup. Although the OCALL thing is a bit of an unknown area, I think all obviously dangerous places are sanitized already, only some more subtle ones are left. But we should resolve it rather sooner than later to not risk having security vulns. But if #1236 is P0 then this can stay at P2.
