### ISSUE TITLE
PAL regression tests on SGX

### ISSUE THREAD

**Issue by HW42** [oscarlab/graphene#498]
Meta ticket to track progress on fixing regression tests on SGX.

TODO list (based on test run with https://github.com/oscarlab/graphene/commit/1e94bb9666488da23de7c453bb8015b68b09511d on Ubuntu 16.04. Checked means fix submitted):

 - [x] Memory Protection (#503)
 - [x] Memory Deallocation (#503)
 - [x] Process Creation (#511)
 - [x] Process Creation Arguments (#511)
 - [x] Process Channel Transmission (#511)
 - [x] Multi-Process Broadcast Channel Transmission (discussion in #501, resolved by #507)
 - [x] Process Creation without Executable (#511)
 - [x] Send and Receive Handles across Processes (#511)
 - [x] Send Pipe Handle (#511)
 - [x] Send Socket Handle (#511)
 - [x] Send File Handle (#511)

**Comment by donporter** [comment]
Thanks!

**Comment by donporter** [comment]
Thanks!

**Comment by HW42** [comment]
Updated with links to issues/PRs. Also submitted #518 to enable the tests on Jenkins. Will keep this open until they are merged.

**Comment by HW42** [comment]
This has been merged a long time ago.
