### ISSUE TITLE
handle_ecall and pal_linux_main trust arguments blindly

### ISSUE THREAD

**Issue by HW42** [oscarlab/graphene#509]
`handle_ecall` and `pal_linux_main` currently don't verify the passed arguments. Since those are coming from the outside this is a security problem.

For example currently `pal_loader` can simply pass an pointer to a manifest outside the enclave which the enclave will accept.

There are many affected fields (`ms_ecall_enclave_start_t` and all it's recursive members). For those we need to check what needs to be done. Usually this will be one of those 3 options, I think:

 1. Don't read the value from the outside at all (use fixed address inside enclave, ask the CPU, etc.).
 2. Copy to enclave memory and then verify it.
 3. In cases where they should be allowed to be changed from the outside (like currently argv, but see #508) we probably still want to copy them inside the enclave to avoid TOCTOU problems later.

---

Implemented in the following PRs (checked means merged):
 - [x] #577: PAL addr/name
 - [x] #580: manifest size/addr
 - [x] #582: manifest/exec fd
 - [x] #588: exec addr/size
 - [x] #589: heap min/max
 - [x] #590: Other args

Some of these PRs will need to be updated depending on merge order of them (and of PR #573).

**Comment by mkow** [comment]
Those fields and their subfields are also missing checks with `sgx_is_within_enclave` (the pointers *must not* point into enclave's address space, otherwise it can lead to leaking enclave memory, or other bad things).

**Comment by HW42** [comment]
The `pal_sec` struct has some fields like `enclave_addr` or `mrenclave` which must be trustworthy and can be checked/calculated inside the enclave. But there are also fields like `ppid` or `uid` which the enclave can't check or calculate. So any use of those parameters needs be careful to not accidentally trust them.

What do you think how this should be handled? Split into two structs, prefix with `untrusted_`, ...

**Comment by dimakuv** [comment]
I don't think we need to have any special namings for such fields as `pal_sec.ppid`. Is there an actual case which demonstrates where a special name would help?

I would suggest to have a minimal number of exceptions with the special naming convention (`untrusted_` is fine). These exceptions are basically pointers to those objects which live in untrusted memory -- e.g. a futex uaddr, a pointer to untrusted OCALL stack, etc. There must be a couple more such cases in the codebase.

All objects residing in enclave memory should not have special namings. For example, ideally `ppid` should be somehow verified during assignment from the outside (yes, we don't have any verifications right now). But after that, we should trust this value because it is not under attacker control any more. And of course, we should copy all objects inside of the enclave to escape TOCTOU issues (except when we technically cannot do that as in the case with futexes).

**Comment by mkow** [comment]
All related PR were just merged, closing.
